<?php

namespace App\Enums;

class LanguageEnum
{
    const AFRIKAANS = 'af';
    const ALBANIAN = 'sq';
    const AMHARIC = 'am';
    const ARABIC = 'ar';
    const ARMENIAN = 'hy';
    const ASSAMESE = 'as';
    const AYMARA = 'ay';
    const AZERBAIJANI = 'az';
    const BAMBARA = 'bm';
    const BASQUE = 'eu';
    const BELARUSIAN = 'be';
    const BENGALI = 'bn';
    const BHOJPURI = 'bho';
    const BOSNIAN = 'bs';
    const BULGARIAN = 'bg';
    const CATALAN = 'ca';
    const CEBUANO = 'ceb';
    const CHINESE_SIMPLIFIED = 'zh-CN'; // or 'zh' (BCP-47)
    const CHINESE_TRADITIONAL = 'zh-TW'; // (BCP-47)
    const CORSICAN = 'co';
    const CROATIAN = 'hr';
    const CZECH = 'cs';
    const DANISH = 'da';
    const DHIVEHI = 'dv';
    const DOGRI = 'doi';
    const DUTCH = 'nl';
    const ENGLISH = 'en';
    const ESPERANTO = 'eo';
    const ESTONIAN = 'et';
    const EWE = 'ee';
    const FILIPINO_TAGALOG = 'fil';
    const FINNISH = 'fi';
    const FRENCH = 'fr';
    const FRISIAN = 'fy';
    const GALICIAN = 'gl';
    const GEORGIAN = 'ka';
    const GERMAN = 'de';
    const GREEK = 'el';
    const GUARANI = 'gn';
    const GUJARATI = 'gu';
    const HAITIAN_CREOLE = 'ht';
    const HAUSA = 'ha';
    const HAWAIIAN = 'haw';
    const HEBREW = 'he'; // or 'iw'
    const HINDI = 'hi';
    const HMONG = 'hmn';
    const HUNGARIAN = 'hu';
    const ICELANDIC = 'is';
    const IGBO = 'ig';
    const ILOCANO = 'ilo';
    const INDONESIAN = 'id';
    const IRISH = 'ga';
    const ITALIAN = 'it';
    const JAPANESE = 'ja';
    const JAVANESE = 'jv'; // or 'jw'
    const KANNADA = 'kn';
    const KAZAKH = 'kk';
    const KHMER = 'km';
    const KINYARWANDA = 'rw';
    const KONKANI = 'gom';
    const KOREAN = 'ko';
    const KRIO = 'kri';
    const KURDISH = 'ku';
    const KURDISH_SORANI = 'ckb';
    const KYRGYZ = 'ky';
    const LAO = 'lo';
    const LATIN = 'la';
    const LATVIAN = 'lv';
    const LINGALA = 'ln';
    const LITHUANIAN = 'lt';
    const LUGANDA = 'lg';
    const LUXEMBOURGISH = 'lb';
    const MACEDONIAN = 'mk';
    const MAITHILI = 'mai';
    const MALAGASY = 'mg';
    const MALAY = 'ms';
    const MALAYALAM = 'ml';
    const MALTESE = 'mt';
    const MAORI = 'mi';
    const MARATHI = 'mr';
    const MEITEILON_MANIPURI = 'mni-Mtei';
    const MIZO = 'lus';
    const MONGOLIAN = 'mn';
    const MYANMAR_BURMESE = 'my';
    const NEPALI = 'ne';
    const NORWEGIAN = 'no';
    const NYANJA_CHICHEWA = 'ny';
    const ODIA_ORIYA = 'or';
    const OROMO = 'om';
    const PASHTO = 'ps';
    const PERSIAN = 'fa';
    const POLISH = 'pl';
    const PORTUGUESE = 'pt';
    const PUNJABI = 'pa';
    const QUECHUA = 'qu';
    const ROMANIAN = 'ro';
    const RUSSIAN = 'ru';
    const SAMOAN = 'sm';
    const SANSKRIT = 'sa';
    const SCOTS_GAELIC = 'gd';
    const SEPEDI = 'nso';
    const SERBIAN = 'sr';
    const SESOTHO = 'st';
    const SHONA = 'sn';
    const SINDHI = 'sd';
    const SINHALA_SINHALESE = 'si';
    const SLOVAK = 'sk';
    const SLOVENIAN = 'sl';
    const SOMALI = 'so';
    const SPANISH = 'es';
    const SUNDANESE = 'su';
    const SWAHILI = 'sw';
    const SWEDISH = 'sv';
    const TAGALOG_FILIPINO = 'tl';
    const TAJIK = 'tg';
    const TAMIL = 'ta';
    const TATAR = 'tt';
    const TELUGU = 'te';
    const THAI = 'th';
    const TIGRINYA = 'ti';
    const TSONGA = 'ts';
    const TURKISH = 'tr';
    const TURKMEN = 'tk';
    const TWI_AKAN = 'ak';
    const UKRAINIAN = 'uk';
    const URDU = 'ur';
    const UYGHUR = 'ug';
    const UZBEK = 'uz';
    const VIETNAMESE = 'vi';
    const WELSH = 'cy';
    const XHOSA = 'xh';
    const YIDDISH = 'yi';
    const YORUBA = 'yo';
    const ZULU = 'zu';

    const LANGUAGE_NAMES = [
        self::AFRIKAANS => 'Afrikaans',
        self::ALBANIAN => 'Albanian',
        self::AMHARIC => 'Amharic',
        self::ARABIC => 'Arabic',
        self::ARMENIAN => 'Armenian',
        self::ASSAMESE => 'Assamese',
        self::AYMARA => 'Aymara',
        self::AZERBAIJANI => 'Azerbaijani',
        self::BAMBARA => 'Bambara',
        self::BASQUE => 'Basque',
        self::BELARUSIAN => 'Belarusian',
        self::BENGALI => 'Bengali',
        self::BHOJPURI => 'Bhojpuri',
        self::BOSNIAN => 'Bosnian',
        self::BULGARIAN => 'Bulgarian',
        self::CATALAN => 'Catalan',
        self::CEBUANO => 'Cebuano',
        self::CHINESE_SIMPLIFIED => 'Chinese (Simplified)',
        self::CHINESE_TRADITIONAL => 'Chinese (Traditional)',
        self::CORSICAN => 'Corsican',
        self::CROATIAN => 'Croatian',
        self::CZECH => 'Czech',
        self::DANISH => 'Danish',
        self::DHIVEHI => 'Dhivehi',
        self::DOGRI => 'Dogri',
        self::DUTCH => 'Dutch',
        self::ENGLISH => 'English',
        self::ESPERANTO => 'Esperanto',
        self::ESTONIAN => 'Estonian',
        self::EWE => 'Ewe',
        self::FILIPINO_TAGALOG => 'Filipino (Tagalog)',
        self::FINNISH => 'Finnish',
        self::FRENCH => 'French',
        self::FRISIAN => 'Frisian',
        self::GALICIAN => 'Galician',
        self::GEORGIAN => 'Georgian',
        self::GERMAN => 'German',
        self::GREEK => 'Greek',
        self::GUARANI => 'Guarani',
        self::GUJARATI => 'Gujarati',
        self::HAITIAN_CREOLE => 'Haitian Creole',
        self::HAUSA => 'Hausa',
        self::HAWAIIAN => 'Hawaiian',
        self::HEBREW => 'Hebrew',
        self::HINDI => 'Hindi',
        self::HMONG => 'Hmong',
        self::HUNGARIAN => 'Hungarian',
        self::ICELANDIC => 'Icelandic',
        self::IGBO => 'Igbo',
        self::ILOCANO => 'Ilocano',
        self::INDONESIAN => 'Indonesian',
        self::IRISH => 'Irish',
        self::ITALIAN => 'Italian',
        self::JAPANESE => 'Japanese',
        self::JAVANESE => 'Javanese',
        self::KANNADA => 'Kannada',
        self::KAZAKH => 'Kazakh',
        self::KHMER => 'Khmer',
        self::KINYARWANDA => 'Kinyarwanda',
        self::KONKANI => 'Konkani',
        self::KOREAN => 'Korean',
        self::KRIO => 'Krio',
        self::KURDISH => 'Kurdish',
        self::KURDISH_SORANI => 'Kurdish (Sorani)',
        self::KYRGYZ => 'Kyrgyz',
        self::LAO => 'Lao',
        self::LATIN => 'Latin',
        self::LATVIAN => 'Latvian',
        self::LINGALA => 'Lingala',
        self::LITHUANIAN => 'Lithuanian',
        self::LUGANDA => 'Luganda',
        self::LUXEMBOURGISH => 'Luxembourgish',
        self::MACEDONIAN => 'Macedonian',
        self::MAITHILI => 'Maithili',
        self::MALAGASY => 'Malagasy',
        self::MALAY => 'Malay',
        self::MALAYALAM => 'Malayalam',
        self::MALTESE => 'Maltese',
        self::MAORI => 'Maori',
        self::MARATHI => 'Marathi',
        self::MEITEILON_MANIPURI => 'Meiteilon (Manipuri)',
        self::MIZO => 'Mizo',
        self::MONGOLIAN => 'Mongolian',
        self::MYANMAR_BURMESE => 'Myanmar (Burmese)',
        self::NEPALI => 'Nepali',
        self::NORWEGIAN => 'Norwegian',
        self::NYANJA_CHICHEWA => 'Nyanja (Chichewa)',
        self::ODIA_ORIYA => 'Odia (Oriya)',
        self::OROMO => 'Oromo',
        self::PASHTO => 'Pashto',
        self::PERSIAN => 'Persian',
        self::POLISH => 'Polish',
        self::PORTUGUESE => 'Portuguese (Portugal, Brazil)',
        self::PUNJABI => 'Punjabi',
        self::QUECHUA => 'Quechua',
        self::ROMANIAN => 'Romanian',
        self::RUSSIAN => 'Russian',
        self::SAMOAN => 'Samoan',
        self::SANSKRIT => 'Sanskrit',
        self::SCOTS_GAELIC => 'Scots Gaelic',
        self::SEPEDI => 'Sepedi',
        self::SERBIAN => 'Serbian',
        self::SESOTHO => 'Sesotho',
        self::SHONA => 'Shona',
        self::SINDHI => 'Sindhi',
        self::SINHALA_SINHALESE => 'Sinhala (Sinhalese)',
        self::SLOVAK => 'Slovak',
        self::SLOVENIAN => 'Slovenian',
        self::SOMALI => 'Somali',
        self::SPANISH => 'Spanish',
        self::SUNDANESE => 'Sundanese',
        self::SWAHILI => 'Swahili',
        self::SWEDISH => 'Swedish',
        self::TAGALOG_FILIPINO => 'Tagalog (Filipino)',
        self::TAJIK => 'Tajik',
        self::TAMIL => 'Tamil',
        self::TATAR => 'Tatar',
        self::TELUGU => 'Telugu',
        self::THAI => 'Thai',
        self::TIGRINYA => 'Tigrinya',
        self::TSONGA => 'Tsonga',
        self::TURKISH => 'Turkish',
        self::TURKMEN => 'Turkmen',
        self::TWI_AKAN => 'Twi (Akan)',
        self::UKRAINIAN => 'Ukrainian',
        self::URDU => 'Urdu',
        self::UYGHUR => 'Uyghur',
        self::UZBEK => 'Uzbek',
        self::VIETNAMESE => 'Vietnamese',
        self::WELSH => 'Welsh',
        self::XHOSA => 'Xhosa',
        self::YIDDISH => 'Yiddish',
        self::YORUBA => 'Yoruba',
        self::ZULU => 'Zulu',
    ];
    /**
     * Get all language codes.
     *
     * @return array
     */
    public static function getAllLanguageCodes()
    {
        $reflectionClass = new \ReflectionClass(self::class);
        return $reflectionClass->getConstants()['LANGUAGE_NAMES'];
    }
}
